name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        
      - name: Download and install Boost
        uses: MarkusJx/install-boost@v1.71.0

        
      - name: Build application
        run: make

      - name: Build test
        run: make test

      - name: Run tests
        run: make run_test
